version: "2"

services:
  webapp:
    extends:
      service: logging
    volumes: 
    - tmp:/tmp
    - thumb:/thumb
    - app:/usr/local/webapp
    - ${LOG_PATH}/tomcat:/usr/local/tomcat/logs
    - ${LOG_PATH}/pmis:/var/log/pmis
    - ${EDMS_PATH}:/edms
    environment:
    - LOGSPOUT=ignore
    - SYSTEM_TIMEZONE
    - JAVA_MAX_SIZE
    - JAVA_OPTS
    - MACHINE_HOST
    - DB_URL
    - DB_PASSWORD
    - DB_USERNAME

  httpd:
    image: sangah/apache-pmis
    extends:
      service: logging
    volumes:
    - app:/var/www
    environment:
    - APACHE_SSL
    - APACHE_SSL_KEY
    - APACHE_SSL_CERT
    - SECURED_RESOURCE_ALLOWED_IP

  upload:
    image: sangah/pmis-fileupload
    extends:
      service: logging
    volumes:
    - tmp:/tmp
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    extends:
      service: logging
    volumes:
    - ngx:/etc/nginx/www

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"