version: "2"

services:
  webapp:
    extends:
      service: logging
    volumes: 
    - thumb:/thumb
    - app:/usr/local/webapp
    - ${TEMP_PATH}:/tmp
    - ${LOG_PATH}/tomcat:/usr/local/tomcat/logs
    - ${LOG_PATH}/pmis:/var/log/pmis
    - ${EDMS_PATH}:/edms
    environment:
    - JAVA_MAX_SIZE
    - JAVA_OPTS
    - MACHINE_HOST
    - PROJECT_NAME
    - DB_URL
    - DB_PASSWORD
    - DB_USERNAME

  httpd:
    image: sangah/nginx-pmis
    extends:
      service: logging
    volumes:
    - app:/var/www
    - ${LOG_PATH}/nginx:/var/log/nginx

  upload:
    image: sangah/pmis-fileupload
    extends:
      service: logging
    volumes:
    - ${TEMP_PATH}:/tmp
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    extends:
      service: logging
    volumes:
    - ngx:/etc/nginx/www

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"