version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
    - SYSTEM_UPLOAD_HANDLER=nginx
    restart: "unless-stopped"

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app
    ports:
    - "${HTTP_PORT}:80"
    - "443:443"
    restart: "unless-stopped"

  upload:
    extends: 
      file: common-services.yml
      service: upload
    restart: "unless-stopped"

  php:
    extends: 
      file: common-services.yml
      service: php
    restart: "unless-stopped"

  rabbitmq:
    extends: 
      file: common-services.yml
      service: rabbitmq
    ports:
    - "${RABBITMQ_HTTP_PORT}:15672"
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  ngx:
  app: