version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
    - JVM_ROUTE=worker1
    - SYSTEM_UPLOAD_HANDLER=nginx

  was2:
    extends: 
      service: was
    environment: 
    - JVM_ROUTE=worker2
    - SYSTEM_UPLOAD_HANDLER=nginx
    restart: "unless-stopped"

  httpd:
    build: httpd
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"

  upload:
    extends: 
      file: common-services.yml
      service: upload
    restart: "unless-stopped"

  php:
    extends: 
      file: common-services.yml
      service: php
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  ngx:
  app: