# Use this for testing the application
# no ssl available
# Access it through the port set with HTTP_PORT
version: "2"

services:
  was:
    image: ${REGISTRY_URL}/tomcat-base
    volumes:
      - tmp:/tmp
      - app:/usr/local/pmis
      - ${EDMS_PATH}:/edms
      - ${LOG_PATH}/tomcat:/usr/local/tomcat/logs
      - ${LOG_PATH}/pmis:/var/log/pmis
      - ./${PROJECT_ARCHIVE}:/usr/local/pmis/pmis.war
      - ./server.xml:/usr/local/tomcat/conf/server.xml

  httpd:
    image: ${REGISTRY_URL}/apache-pmis
    links:
      - was
      - upload
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - app:/var/www
    environment:
      - APACHE_SSL=0

  upload:
    image: ${REGISTRY_URL}/pmis-fileupload
    #ports:
      #- "18180:8180"
    volumes:
      - tmp:/tmp
      - ngx:/etc/nginx/www
    links:
      - php

  php:
    image: php:5.6-fpm
    volumes:
      - ngx:/etc/nginx/www

volumes:
  edms:
  tmp:
  ngx:
  app: