version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
    - "system.upload.handler=nginx"
    networks:
    - pmis-network
    restart: "unless-stopped"

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    depends_on: 
    - was
    networks: 
      pmis-network:
      hub_net:
        aliases: 
        - ${HUB_INSTANCE}
    restart: "unless-stopped"

volumes:
  thumb:
  app:
  tmp:
    external: true

networks:
  pmis-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
  hub_net:
    external: true