version: "2"

services:
  was:
    extends: 
      file: common-services.yml
      service: webapp

  httpd:
    extends: 
      file: common-services.yml
      service: httpd

  upload:
    extends: 
      file: common-services.yml
      service: upload

  php:
    image: php:5.6-fpm
    volumes:
      - ngx:/etc/nginx/www

volumes:
  tmp:
  thumb:
  ngx:
  app: