version: "2"

services:

  httpd:
    ports:
    - "${HTTPS_PORT}:443"
    environment: 
    - SSL_ENABLED=1
    volumes:
    - $SSL_CERT:/usr/share/nginx/ssl/nginx.crt
    - $SSL_KEY:/usr/share/nginx/ssl/nginx.key
    