version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
      - JVM_ROUTE=worker1

  was2:
    extends: 
      service: was
    environment: 
      - JVM_ROUTE=worker2

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpd/workers.properties:/etc/libapache2-mod-jk/workers.properties

  upload:
    extends: 
      file: common-services.yml
      service: upload
    links:
      - php

  php:
    extends: 
      file: common-services.yml
      service: php

volumes:
  tmp:
  thumb:
  ngx:
  app: