version: "2"

services:

  livechat:
    image: sangah/livechat
    environment: 
    - CLIENT_AUTH_ENABLED=true
    - CLIENT_AUTH_ENDPOINT=http://httpd/
    - CLIENT_PROFILE_ENDPOINT=http://httpd/System/User/findUser.action
    - SERVER_WEBROOT=/livechat
    networks:
    - pmis-network
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"