version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
    - JVM_ROUTE=worker1
    - SYSTEM_UPLOAD_HANDLER=nginx

  was2:
    extends: 
      service: was
    environment: 
    - JVM_ROUTE=worker2
    - SYSTEM_UPLOAD_HANDLER=nginx
    restart: "unless-stopped"

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app
    networks: 
      default:
      hub_net:
        aliases: 
        - ${HUB_INSTANCE}
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  app:

networks: 
  hub_net:
    external: true