# Use this for testing the application
# no ssl available
# Access it through the port set with HTTP_PORT
version: "2"

services:
  was:
    build: was
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
    - SYSTEM_UPLOAD_HANDLER=nginx

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    ports:
      - "${HTTP_PORT}:80"
    environment:
      - APACHE_SSL=0

  upload:
    extends: 
      file: common-services.yml
      service: upload

  php:
    extends: 
      file: common-services.yml
      service: php

volumes:
  thumb:
  tmp:
  ngx:
  app: