version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment:
    - "system.upload.handler=nginx"
    networks:
    - pmis-network
    restart: "unless-stopped"

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - $SSL_CERT:/usr/share/nginx/ssl/nginx.crt
    - $SSL_KEY:/usr/share/nginx/ssl/nginx.key
    ports:
    - "${HTTP_PORT}:80"
    depends_on: 
    - was
    networks:
    - pmis-network
    restart: "unless-stopped"

  upload:
    extends: 
      file: common-services.yml
      service: upload
    networks:
    - pmis-network
    restart: "unless-stopped"

  php:
    extends: 
      file: common-services.yml
      service: php
    networks:
    - pmis-network
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  ngx:
  app:

networks:
  pmis-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
