version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment: 
      - JVM_ROUTE=worker1

  was2:
    extends: 
      service: was
    environment: 
      - JVM_ROUTE=worker2

  httpd:
    build: httpd
    image: apache-pmis:cluster
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app
    ports:
      - "80:80"
      - "443:443"

  upload:
    extends: 
      file: common-services.yml
      service: upload
    links:
      - php

  php:
    extends: 
      file: common-services.yml
      service: php

volumes:
  tmp:
  thumb:
  ngx:
  app: