# Use this for testing the application
# no ssl available
# Access it through the port set with HTTP_PORT
version: "2"

services:
  was:
    build: was
    extends: 
      file: common-services.yml
      service: webapp
    ports:
      - "${HTTP_PORT}:8080"

volumes:
  thumb:
  tmp:
  app: