version: "2"

services:
  certbot:
    image: sangah/nginx-certbot
    volumes:
    - ${CERTBOT_CERTS_PATH}:/etc/letsencrypt
    - app:/usr/share/nginx/html
    environment:
    - CERTBOT_HOST
    - CERTBOT_EMAIL
    - CERTBOT_STANDALONE=false
    - CERTBOT_CERTS_PATH
    depends_on: 
    - httpd