version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    ports:
    - "${HTTP_PORT}:8080"
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  app: